### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [JLChnToZ/lazy-loader#1]
Hi @JLChnToZ I contribute to open source projects in my free time. I reviewed your project and i noticed  this project did not have a logo. how about using this logo? Please let me know if you have any requests. I will wait for feedback. Have a nice day!

![LAZYLOADER](https://user-images.githubusercontent.com/36298335/56041436-6a593780-5d41-11e9-9fbf-12fe17b27927.jpg)

**Comment by JLChnToZ** [comment]
Wow! I have never thought about adding a logo for my JS modules. Your designs are nice and it is welcome to contribute!

**Comment by JLChnToZ** [comment]
Also, because the name of "lazy-loader" has been taken by [other module in NPM](https://www.npmjs.com/package/lazy-loader), so the real name of the project is [Lazy Initializer](https://www.npmjs.com/package/lazy-initializer). Before you contribute, you may have to change the name, thanks!

**Comment by reallinfo** [comment]
Oh okay, Which of these variations do you like? I'll send a pr for your variation request.

![lazyin](https://user-images.githubusercontent.com/36298335/56079251-9edcfa00-5dfa-11e9-977e-589f2845c81c.jpg)

**Comment by JLChnToZ** [comment]
Three of them looks great! But if you ask me, I will choose the third one, maybe.

**Comment by reallinfo** [comment]
i sent a pr and i updated the readme file. (I've put the logo variation you like into the readme file.) you can change it if you want. All variations are available.

**Comment by JLChnToZ** [comment]
Ok, thanks!
